export {
  getInspectionDetail,
  getInspectionSlots,
  startInspection,
  startNextInspection,
  skipInspection,
  uploadInspectionImage,
  ocrInspectionImage,
  saveInspectionResults,
  completeInspection,
  incompleteInspection,
  reopenInspection,
} from "./inspectionApi";
export {
  useInspectionDetail,
  useInspectionSlots,
  useSlotSequences,
  useStartInspection,
  useStartNextInspection,
  useSkipInspection,
  useUploadInspectionImage,
  useOcrInspectionImage,
  useSaveInspectionResults,
  useCompleteInspection,
  useIncompleteInspection,
  useReopenInspection,
  inspectionKeys,
} from "./queries";
